### ISSUE TITLE
CASO 1.3

### ISSUE THREAD

**Issue by temple** [coollectica/PracticaEvCont2#1]
https://github.com/coollectica/PracticaEvCont2/blob/25894cf5bd8bd1a81f566e08a605d27b515d9310/actividad2.js#L21

**Comment by XaviGV** [comment]
Parte del codigo en el que aparece una sentencia FOR sin el "in".
De las lineas 38 a 58. En la linea 44 aparece la sentencia FOR aislada, en la que dentro aparece otra sentencia for...in.
```
function extend() {
  var obj, name, copy,
      target = arguments[0] || {},
      i = 1,
      length = arguments.length;

  for (; i < length; i++) {
    if ((obj = arguments[i]) !== null) {
      for (name in obj) {
        copy = obj[name];

        if (target === copy) {
          continue;
        } else if (copy !== undefined) {
          target[name] = copy;
        }
      }
    }
  }
  return target;
} 
```

**Comment by coollectica** [comment]
Código seleccionado
```
  for (var i = 0; i < count; i++) {
    str += '<div></div>';
  }
```

for  - Crea un bucle que consiste en tres expresiones opcionales, encerradas en paréntesis y separadas por puntos y comas, seguidas de una sentencia ejecutada en un bucle.
Sintaxis
for ([expresion-inicial]; [condicion]; [expresion-final])sentencia

**Comment by bitcoinoperated** [comment]
1. La explicación es demasiado vaga.
2. El fragmento de código es incorrecto. Muestra la declaración "for ... in" en lugar de la declaración "for".
3. El enlace a MDN no es lo suficientemente preciso.

# Mi solución.
1.3: "Fragmento de código donde aparezca la sentencia iterativa 'for' y donde se use una variable para iterar."

La declaración "for" se usa para crear un bucle con 3 expresiones opcionales entre paréntesis (redondo), que es seguido por una declaración en otra paréntesis (rizado).
En este ejemplo, podemos ver la creación de bucle invocando la declaración "for" que tiene 3 expresiones "var i = 0", "i <3" e "i ++".
La instrucción "for" es seguida por otra instrucción en paréntesis redondo (llaves).
Linea 130-137.
/Podemos ver la documentación de MDN que explica la creación de var en este enlace:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for

```
for (var i = 0; i < 3; i++) {
  val = vals[i];
  div.style.width = val;
  if (div.offsetWidth === 100) {
  result = val.replace(str, '');
  break;
  }
  }
```

**Comment by LokiSkog8** [comment]
``var i = 0;
for (; i < 9; i++) {
    console.log(i);
    // more statements
}´´

**Comment by temple** [comment]
En la línea 24 pone 

> L'**event** que executa la iteració for apareix a la linia 435 amb la variable

La palabra _event_ hay que cambiarla por _sentencia_, porque justamente el `for` es un tipo de sentencia.

**Comment by temple** [comment]
En la propuesta https://github.com/coollectica/PracticaEvCont2/issues/1#issuecomment-581821330 se usa la variable `i` que se crea en la línea 41 del código original.

**Comment by XaviGV** [comment]
Modificada la respuesta y cambiada la función usada para ajustar mas a lo que requiere el caso por un FOR aislado

```
/*Cas 1.3: Fragment de codi on aparegui la sentència iterativa for i on es faci servir una variable per a iterar.
Linea 38 a 58
La sentencia que executa la iteració for apareix a la linia 44 amb la variable i que es crea a la linea 41 del codi 
https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Bucles_e_iteraci%C3%B3n
 */ 

function extend() {
  var obj, name, copy,
      target = arguments[0] || {},
      i = 1,
      length = arguments.length;

  for (; i < length; i++) {
    if ((obj = arguments[i]) !== null) {
      for (name in obj) {
        copy = obj[name];

        if (target === copy) {
          continue;
        } else if (copy !== undefined) {
          target[name] = copy;
        }
      }
    }
  }
  return target;
} 

```
