### ISSUE TITLE
CASO 4.4

### ISSUE THREAD

**Issue by jkacosta** [coollectica/PracticaEvCont2#13]
https://github.com/coollectica/PracticaEvCont2/blob/25894cf5bd8bd1a81f566e08a605d27b515d9310/actividad2.js#L345

**Comment by coollectica** [comment]
/* 4.4: Fragmento de código donde aparezca el acceso a un objecte del BOM */
//LÍNEA 32
//Lo que propusimos en un principio (setTimout) es erróneo, porque no estamos accediendo a ningún objeto del BOM.
//Los objetos dels BOM se pueden ver en:
//https://www.arkaitzgarro.com/javascript/capitulo-14.html#control-de-tiempos
//Por lo tanto mejo cambiamos la propuesta de código por la siguiente:

```
var win$1 = window;
```
// una linea de código que crea una variable, y a ésta se le asigna el objeto window
